### ISSUE TITLE
Graphics stopped working

### ISSUE THREAD

**Issue by sschloesser** [Thermondo/heroku-buildpack-tex#17]
Not sure if this issue is because of this buildpack, but an `\includegraphics` statement stopped working out of nowhere and I didn't change anything on my end. I've tried clearing the build cache and redeploying, and reuploading the image and all sorts of things with no luck. The latex output also shows no errors. It works on my local machine, but that's not such a good indicator because I have the full tex installation there. Anyway, if you know of something that could be causing this or how to debug this I would appreciate the insights!

**Comment by codingjoe** [comment]
Hi @sschloesser I know debugging these can be hard. I did setup a little docker based test suite right here: #18 

I would recommend adapting it to your needs and building it locally to debug your issues.
Here is how you can do that:

1. Checkout the `tests` branch.
2. Add your `texlive.profile` or `texlive.packages` file to the repo root.
3. Run `docker build . -t heroku-tex`
4. Run `docker run -ti -v PATH/TO/TEST/TEX/FILE/DIR /app/examples heroku-tex`

That will put you inside a heroku container with your exact packages installed. Can can than run your TeX commands and debug whatever is wrong.

I hope that helps you :)

**Comment by sschloesser** [comment]
@codingjoe thanks so much for the help! It's extremely useful to have this container for testing. The \includegraphics worked on it, so I guess on heroku it must be an issue with the image file or it's path or something along those lines, so we can probably close the issue.

**Comment by anneFly** [comment]
@sschloesser I don't know if it might be helpful for your case but we had also an issue where some graphics stopped working with `\includegraphics`. In our case it was because the graphics were some generated thumbnails and somehow TeX Live 2017 has a problem with that. Our fix was installing TeX Live 2016 because there it worked. You can tell the buildpack the path it should use for the installer. just how it is documented here: https://github.com/Thermondo/heroku-buildpack-tex#custom-tex-live-version

Maybe that helps your case as well. Btw, if it does help, please make sure you are referencing the buildpack in heroku with the version number because we might soon introduce a breaking change where the file path is changed. Just as a heads up.

**Comment by sschloesser** [comment]
Thanks @anneFly for the heads up! It turned out the problem was that I was using quotes around the image path `\includegraphics{"path/to/image.png"}` and removing them fixed it. So this buildpack changed from using Tex Live 2016 to 2017? Maybe that's what broke it because it was working before.

**Comment by codingjoe** [comment]
@sschloesser it always uses the latest version by default. But you can freeze the repo to a certain version, as @anneFly suggested.
